import { bigint, index, integer, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';

import { user } from './schema';

/**
 * Application tables.
 *
 * Kept out of schema.ts because that file is regenerated by
 * `@better-auth/cli generate`, which overwrites whatever is in it.
 *
 * `timestamp(..., { mode: 'date' }).defaultNow()` replaces the SQLite version's
 * `integer(..., { mode: 'timestamp_ms' })` epoch-ms columns with Postgres's
 * native timestamp type — Drizzle still hands back a JS `Date` either way, so
 * nothing downstream needed to change.
 */

/**
 * A user-defined grouping of channels.
 *
 * Replaces the hardcoded 9-12 standards. Those were only ever right for one
 * board and one age range — tracking Class 8, a set of personal channels, or a
 * subject-specific group all needed the same mechanism, so the grouping is data
 * rather than an enum.
 */
export const workspace = pgTable(
  'workspace',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    /** URL-safe key; what `?ws=` carries so a scoped view stays shareable. */
    slug: text('slug').notNull(),
    /** Manual ordering in the switcher. */
    position: integer('position').notNull().default(0),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull()
  },
  (t) => [uniqueIndex('workspace_user_slug').on(t.userId, t.slug)]
);

/**
 * Channel membership. Many-to-many on purpose: "PW Maharashtra 9&10" belongs in
 * both a Class 9 and a Class 10 workspace, and a personal channel might sit in
 * several unrelated ones.
 */
export const channelWorkspace = pgTable(
  'channel_workspace',
  {
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    trackedChannelId: text('tracked_channel_id')
      .notNull()
      .references(() => trackedChannel.id, { onDelete: 'cascade' })
  },
  (t) => [uniqueIndex('channel_workspace_pair').on(t.workspaceId, t.trackedChannelId)]
);

/** A channel a user has chosen to track. Replaces the localStorage list. */
export const trackedChannel = pgTable(
  'tracked_channel',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    /** The handle or `UC…` id as entered; resolution happens at read time. */
    channelId: text('channel_id').notNull(),
    handle: text('handle'),
    title: text('title'),
    /** Which section it renders under: own, faculty, ssc, hsc. */
    groupKey: text('group_key').notNull().default('ssc'),
    /** JSON array of standards, e.g. "[9,10]". Empty means every workspace. */
    standards: text('standards').notNull().default('[]'),
    note: text('note'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull()
  },
  (t) => [uniqueIndex('tracked_channel_user_channel').on(t.userId, t.channelId)]
);

/**
 * Point-in-time channel totals.
 *
 * This is what turns single readings into history: subscriber and view deltas
 * are only computable once two snapshots exist.
 */
export const channelSnapshot = pgTable(
  'channel_snapshot',
  {
    id: text('id').primaryKey(),
    channelId: text('channel_id').notNull(),
    // bigint, not integer: SQLite's integer columns have no fixed width, so
    // this ran for months without issue there. Postgres's plain `integer` caps
    // at ~2.1 billion, which a multi-year channel's lifetime view count clears
    // easily — the migration off SQLite failed on exactly this the first time,
    // on a real channel already past 5.5 billion views.
    subscribers: bigint('subscribers', { mode: 'number' }),
    totalViews: bigint('total_views', { mode: 'number' }),
    videoCount: integer('video_count'),
    capturedAt: timestamp('captured_at', { mode: 'date' }).defaultNow().notNull()
  },
  (t) => [index('channel_snapshot_channel_time').on(t.channelId, t.capturedAt)]
);

/**
 * Point-in-time per-video readings.
 *
 * Storing title and thumbnail alongside views is deliberate: comparing
 * consecutive rows is how a title or thumbnail swap becomes detectable, which
 * is the closest observable proxy for a creator's own A/B test — YouTube never
 * exposes the test itself.
 */
export const videoSnapshot = pgTable(
  'video_snapshot',
  {
    id: text('id').primaryKey(),
    channelId: text('channel_id').notNull(),
    videoId: text('video_id').notNull(),
    title: text('title').notNull(),
    thumbnail: text('thumbnail'),
    // Same bigint reasoning as channelSnapshot — a single video can realistically
    // clear a plain integer's ~2.1B ceiling too.
    views: bigint('views', { mode: 'number' }),
    /**
     * Which endpoint this reading came from.
     *
     * Essential, not bookkeeping: YouTube serves different title variants on
     * different surfaces, so the RSS feed and the channel listing can disagree
     * about the same video at the same moment. Comparing across sources
     * reported those disagreements as creator edits.
     */
    source: text('source', { enum: ['rss', 'deep'] })
      .notNull()
      .default('rss'),
    capturedAt: timestamp('captured_at', { mode: 'date' }).defaultNow().notNull()
  },
  (t) => [
    index('video_snapshot_video_time').on(t.videoId, t.capturedAt),
    index('video_snapshot_channel_time').on(t.channelId, t.capturedAt)
  ]
);

/** A detected title or thumbnail swap between two consecutive snapshots. */
export const videoChange = pgTable(
  'video_change',
  {
    id: text('id').primaryKey(),
    channelId: text('channel_id').notNull(),
    videoId: text('video_id').notNull(),
    field: text('field', { enum: ['title', 'thumbnail'] }).notNull(),
    previousValue: text('previous_value'),
    newValue: text('new_value'),
    /** Views at the moment the change was observed, for before/after context. */
    viewsAtChange: bigint('views_at_change', { mode: 'number' }),
    detectedAt: timestamp('detected_at', { mode: 'date' }).defaultNow().notNull()
  },
  (t) => [index('video_change_channel_time').on(t.channelId, t.detectedAt)]
);
